### ISSUE TITLE
Add ability to set endpoints to the Config class instances

### ISSUE THREAD

**Issue by coderimus** [adobe/stock-api-libphp#17]
# Issue report
Hello, my name is Alex. I am a [Magento Adobe Stock Integration (ASI)](https://github.com/magento/adobe-stock-integration) contributor. In the scope of the ASI project, we work on the stub implementation which should allow us to run tests without connecting to the Adobe Stock service using the internet. This because of the licenses (API tokens).

The problem I faced during the work on the stub is to how to emulate getting data from the AdobeStock. The most suitable solution would be to be able to set endpoints directly to the Config class instance with the constructor. With this approach, we can provide different endpoints to emulate responses from the Adobe Stock service without any modification to the library or implementation based on it.

Currently, the PHP SDK does it like this: https://github.com/adobe/stock-api-libphp/blob/master/src/Core/Config.php#L48 In that case, you are not able to provide your own endpoints, for example, for the stub you create.

What I want to suggest:

Add $endpoints like an optional parameter to the https://github.com/adobe/stock-api-libphp/blob/master/src/Core/Config.php#L45 - `array $endpoings = []`
If this parameter is the empty array we will set endpoints equal to the https://github.com/adobe/stock-api-libphp/blob/master/src/Core/Config.php#L45

Where this can be used? For example, here https://github.com/adobe/stock-api-libphp/blob/master/src/Client/AdobeStock.php#L84 during the AdobeStock client initialization. I can provide the list of endpoints to the Config objects. Those endpoints can be stub's endpoints.

If this idea will be approved I will implement a solution.

## URL or PR where issue occurs
N/A

## Brief description of issue
N/A

## Proposed fix (if applicable)
Described above

If you have a proposed solution, please submit a pull request! See the [contributing guidelines](CONTRIBUTING.md), and thanks for your contribution :)

**Comment by coderimus** [comment]
@sivaschenko please, check this also.

**Comment by chfabbro** [comment]
Hi @coderimus. I appreciate your thoughts on this, and welcome suggestions to make the SDK more robust. Would it be possible to move this conversation to email, to stockapis@adobe.com? I'm not sure which email is best for you, so perhaps you could drop me an email there and I can resume the conversation. I would like to include some colleagues from Adobe who are not on this public GitHub repo.

To be honest, I'm not completely familiar with how tests work in this SDK, as it was initially built a few years back by an external team who is now reassigned; our Stock API team has inherited it, but only the Magento team is actively working on it. So @sivaschenko would be the best one to respond I think.

Are you asking mainly about authenticated requests? Those require a sign-in event to generate an access token, and are required for licensing actions, such as downloading an original image. But we also support requests that only need an API key; we refer to those as "unauthenticated."

In the code base for our APIs, we have different levels of testing, and I imagine this SDK has something similar in the [/test](https://github.com/adobe/stock-api-libphp/tree/master/test) folder. Unit tests typically do not require an internet connection; those use dummy fixtures only (static responses we hard-code). Integration tests, however, test that the different APIs are responding as expected, which may require getting an access token.

Overall, I'm not 100% clear on your request. You would want to be able to supply a list of stub endpoints so that you can provide your own static test responses? I'm pretty sure the testing framework already supports that, by mocking the response if you don't want to call the live API. But again, I'm not totally familiar with the SDK architecture. In any case, I think you would need to submit your own PR for this, as we do not actively contribute to this SDK; we only maintain it.

Please drop us an email at stockapis@adobe.com and we can add some more folks to the thread if you want to discuss further.

Thanks, Christopher

**Comment by coderimus** [comment]
Hello @chfabbro,

Thank you for your response and provided details about the SDK. I talked to @sivaschenko, and he helped me with describing how we can use SDK for creating a stub. We will implement HttpInterface for our needs and create a stub for the Afobe Stock service response.

Thanks, Alex
