### ISSUE TITLE
What is this project licensed under?

### ISSUE THREAD

**Issue by filmaj** [adobe/stock-api-libphp#2]
Would be good to clarify that 😄 

I was also going to send contribution guidelines and a code of conduct. I can send a PR with all of this in one fell swoop?

Lemme know your thoughts.

**Comment by chfabbro** [comment]
All of our SDKs used to reside at this single location, but then I decided it would be better to keep them separate:
https://github.com/adobe/stock-api-sdk

Today, each SDK folder contains a link to the new location. Perhaps it may be enough to provide a link from each individual SDK back to this "home" page, since it has all of those documents?

In any case, the SDK for PHP has an Apache 2 license, which is in the composer.json file:
https://github.com/adobe/stock-api-libphp/blob/master/composer.json

**Comment by filmaj** [comment]
I would say for these two documents specifically it is worthwhile to have them embedded in each repo independently. I believe the de-facto way of figuring out what license a software is under is by looking for a `LICENSE` file in the repo. GitHub's UI also keys on this, and [GitHub's help encourages this as a best practice](https://help.github.com/articles/licensing-a-repository/#determining-the-location-of-your-license) too. So I will encourage this practice as well! If a project has a `CONTRIBUTING.md` file (and same goes for `CODE_OF_CONDUCT.md` and issue+pull request templates), [it gets referenced by GitHub's UI when filing an issue or composing a pull request](https://blog.github.com/2012-09-17-contributing-guidelines/#contributors-wanted-inquire-within), so in that spirit we'd like for it to be present in each repo separately.

With your blessing I can send a PR to ensure we have all of this present for all three language implementations of this SDK?

**Comment by chfabbro** [comment]
Yes, of course.
